loglevel = 5
workspace = "/home/dj/workspace/github.com/nezha/nezha-chat-backend"
root_package_slash = 3

secrete = "secrete"


[memory_cache]
#token的过期时间是100分钟
default_expiration = 100
#清理周期
interval_clear = 10

[rabbitmq]
user = "guest"
password = "guest"
host = "127.0.0.1"
port = 5672

[etcd]
addrs = ["etcd:2379"]
register_ttl = 15
register_interval = 10

[jaeger]
url = "jaeger:6831"
service_name = "auth_srv"

[micro]
name = "nezha.chat.auth.srv.service"
version = "1"