loglevel = 5

#mysql 参数配置
[mysql]
debug = true
# 连接地址
host = "127.0.0.1"
# 连接端口
port= 3306
# 用户名
user = "debian-sys-maint"
# 密码
password = "MuiW0yUkdALNBjcZ"
# 数据库
db_name = "v2_device_info"
# 连接参数
parameters = "charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true"

[rabbitmq]
user = "guest"
password = "guest"
host = "127.0.0.1"
port = 5672

[etcd]
addrs = ["127.0.0.1:2379"]
register_ttl = 15
register_interval = 10



[micro]
name = "nezha.chat.user.srv.service"
version = "1"