loglevel = 5
workspace = "/home/dj/workspace/github.com/nezha/nezha-chat-backend"
root_package_slash = 3

[rabbitmq]
user = "guest"
password = "guest"
host = "192.168.0.128"
port = 5672
chat_exchange_name = "nezha.chat.main"

[etcd]
addrs = ["127.0.0.1:2379"]
register_ttl = 15
register_interval = 10

[jaeger]
url = "127.0.0.1:6831"
service_name = "chat_srv"


[micro]
name = "nezha.chat.chat.srv.service"
version = "1"