loglevel = 5
workspace = "/home/dj/workspace/github.com/nezha/nezha-chat-backend"
root_package_slash = 3

[rabbitmq]
user = "guest"
password = "guest"
host = "rabbitmq"
port = 5672
chat_exchange_name = "nezha.chat.main"

[etcd]
addrs = ["etcd:2379"]
register_ttl = 15
register_interval = 10

[jaeger]
url = "jaeger:6831"
service_name = "chat_srv"

[micro]
name = "nezha.chat.chat.srv.service"
version = "1"